---
- name: Deploy the NFS server
  apt:
    name: "nfs-kernel-server"
    state: latest

- name: Create share for nfs server
  file:
    path: "/dev/utils"
    state: directory
    owner: nobody
    group: nogroup

- name: Setup share in /etc/exports
  lineinfile:
    path: /etc/exports
    line: '/dev/utils *(rw,sync,no_subtree_check)'
    create: yes
  notify:
    - Restart nfs
