---
- name: Create a user with sudo privileges
  hosts: all
  become: yes
  tasks:
    - name: Create a new user
      user:
        name: mary  # Replace with desired username
        password: "{{ 'your_password' | password_hash('sha512') }}"  # Replace 'your_password' with the actual password
        shell: /bin/bash
        state: present

    - name: Add user to sudo group
      user:
        name: mary  # Replace with the same username
        groups: sudo  # On Debian/Ubuntu; for CentOS/RHEL, use 'wheel'
        append: yes

    - name: Allow passwordless sudo for the user (Debian/Ubuntu)
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^mary'
        line: 'mary ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'

    # Optional: For RedHat/CentOS systems, you may need to adjust sudoers configuration
    - name: Allow passwordless sudo for the user (CentOS/RHEL)
      lineinfile:
        path: /etc/sudoers.d/mary
        state: present
        line: 'mary ALL=(ALL) NOPASSWD:ALL'
        create: yes
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
